### ISSUE TITLE
Functions naming consistency

### ISSUE THREAD

**Issue by ellessenne** [brittanyblouin/ANCRTAdjust#12]
Just a minor thing, but I would go crazy trying to remember if functions are `HIV_*()` (with the underscore after HIV) or `HIV*()` (without the underscore) - I would get it wrong all the time!
I would suggest choosing a format and using it throughout the package for consistency.

**Comment by seabbs** [comment]
Agreed. 

Also true for function arguments. 

## Example

In `descriptive_plot` I see ` ylim.ind_min` and `plot_type`. I'd prefer consistent use of `.` or `_` (I tend to always go with `_`). 

I also see `byyear` in `HIVprev_ipcw` which should be either `by.year` or `by_year`. 

For this #openjournals/joss-reviews/issues/1740 review

**Comment by m-maheu-giroux** [comment]
I totally agree with both of you. The previous naming convention was very confusing. I have standardized all function names, arguments, and outputs.

**Comment by ellessenne** [comment]
Great, thanks - if @seabbs agrees (thumbs up is enough) I think you can close this issue.
