### ISSUE TITLE
descriptive_plot axis limits

### ISSUE THREAD

**Issue by seabbs** [brittanyblouin/ANCRTAdjust#19]
Do these need to be manually specified? 

The current default shows the complete percentage range which in most circumstances is not going to be ideal when trying to understand trends over time (which is my interpretation of what this function is doing). 

My preference would be to have no specified range and rely on `ggplot2` defaults. User can then add limits as required. 

What are your thoughts on this? 

For this # [openjournals/joss-reviews/issues/1740](https://github.com/openjournals/joss-reviews/issues/1740)  review

**Comment by m-maheu-giroux** [comment]
We also initially wondered if it would be best to just use the default but decided against this. The issue being that prevalence and testing coverage could potentially exhibit important variations over time and across facilities. Comparing them using standardized default values makes more sense.

**Comment by seabbs** [comment]
Okay - happy to go with you on this. 

However, it can be difficult to see both trends over time and differences between groups if the groups are on very difficult scales. The current plot obscures trends if there are large differences. Might want to discuss this a little in the docs or provide a standardised option (for trends vs. differences).

**Comment by m-maheu-giroux** [comment]
Fair point. I have implemented your requested changes and switched to default. Users still have the option of using their own supplied limits for the y-axis

**Comment by seabbs** [comment]
Okay great - thanks! 


(looks like the README needs updating)
