### ISSUE TITLE
`improv_adjust` combining two functions into one. 

### ISSUE THREAD

**Issue by seabbs** [brittanyblouin/ANCRTAdjust#23]
I see `improv_adjust` and `improv_adjust_simple` - can these functions be combined? 

If not why not? 

Overall I think some more detail on the differences between these two would be good.

**Comment by m-maheu-giroux** [comment]
The two functions have been combined. There is no major differences between the two functions... simply that one uses point estimates for HIV prevalence and HIV testing coverage whereas the other one uses a data frame as input.

**Comment by seabbs** [comment]
Great - thanks (I see some good changes to function arguments as well 👍 ). 

Could you link to changes (i.e the commit or pull request) in the review issues - really helps me keep track of what is happening!
