### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by seabbs** [brittanyblouin/ANCRTAdjust#24]
Found a few spelling issues in the docs - although far fewer that in mine!

I recommend the spelling package for automatic spell checking. See [here](https://github.com/seabbs/getTBinR/blob/master/tests/spelling.R) for an example implementation.

For this # [openjournals/joss-reviews/issues/1740](https://github.com/openjournals/joss-reviews/issues/1740)  review

**Comment by m-maheu-giroux** [comment]
We have integrated your suggestion. Thanks!

**Comment by seabbs** [comment]
Great - I assume that the spelling issues both reviewers identified in pull requests have been sorted?
