### ISSUE TITLE
Add more details on descriptive plots

### ISSUE THREAD

**Issue by ellessenne** [brittanyblouin/ANCRTAdjust#7]
I think it's great that you can produce a "full" descriptive plot or single plots - however, I think it'd be great to describe the single plots in more detail in the README file (at least briefly).
I think it'd be enough to include/describe the options included in the help file (again, briefly) - nothing major!

**Comment by m-maheu-giroux** [comment]
Thanks for the suggestion. 
A more thorough description has been added.
